## Colors configuration
colors:
  # Default colors
  primary:
    background: '#04142D'
    foreground: '#eaccc4'

  # Normal colors
  normal:
    black:   '#04142D'
    red:     '#1F6D8B'
    green:   '#606F88'
    yellow:  '#2D94A9'
    blue:    '#59A5B1'
    magenta: '#58BDC9'
    cyan:    '#AABFBD'
    white:   '#eaccc4'

  # Bright colors
  bright:
    black:   '#a38e89'
    red:     '#1F6D8B'
    green:   '#606F88'
    yellow:  '#2D94A9'
    blue:    '#59A5B1'
    magenta: '#58BDC9'
    cyan:    '#AABFBD'
    white:   '#eaccc4'
